@admin_token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX3R5cGUiOiJhZG1pbiIsInVzZXJuYW1lIjoic3VwZXIuYWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtcHJlc2EuY29tIiwiaWF0IjoxNzU3NDUwMDE1LCJleHAiOjE3NTc0NTM2MTV9.vB02Ub0RBO_t9kKL0WHJCk5rsjHU08U6ma3e8rpFCQo

###REGISTRAR USUARIO
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "username": "cliente2",
  "ruc": "10012345678",
  "password": "PasswordSeguro1234",
  "email": "cliente2@example.com",
  "name": "Mina XYZ S.A.C.",
  "phone": "987654321",
  "userType": "client",
  "status": "active",
  "observations": "Cliente potencial",
  "usualProductsNotes": "Necesita explosivos",
  "ccEmails": "gerencia.mina@example.com",
  "leadTimeDays": 1,
  "user_code": "123456"
}



# {
#   "username": "cliente-mina-xyz",
#   "ruc": "10012345678",
#   "password": "PasswordSeguro123",
#   "email": "cliente.xyz@example.com",
#   "name": "Mina XYZ S.A.C.",
#   "phone": "987654321",
#   "userType": "client",
#   "status": "active",
#   "observations": "Nuevo cliente potencial",
#   "usualProductsNotes": "Necesita explosivos y aditivos",
#   "ccEmails": "gerencia.mina@example.com",
#   "leadTimeDays": 1
# }

# {
#   "username": "super.admin",
#   "password": "UnaContraseñaFuerte1235",
#   "email": "admin@empresa.com",
#   "name": "Juan Pérez",
#   "phone": "999888777",
#   "userType": "admin",
#   "status": "active"
# }



###LISTAR USUARIOS
GET http://localhost:3000/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX3R5cGUiOiJhZG1pbiIsInVzZXJuYW1lIjoic3VwZXIuYWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtcHJlc2EuY29tIiwiaWF0IjoxNzU2ODI3MDk2LCJleHAiOjE3NTY4MzA2OTZ9.rKcKIYUT_xPNZBZbCqgqT0Ps80VZERsm_Ikbhbchdho


###EDITAR USUARIO
PUT http://localhost:3000/api/users/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX3R5cGUiOiJhZG1pbiIsInVzZXJuYW1lIjoic3VwZXIuYWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtcHJlc2EuY29tIiwiaWF0IjoxNzU2ODI3NTU1LCJleHAiOjE3NTY4MzExNTV9.2blx_RKBdjijX6TSc_uwBdwNFHQysnT0WRcphujBvTU
Content-Type: application/json

{
  "name": "Juanjo",
  "phone": "999888778",
  "user_code": "123456"
}

###ELIMINAR USUARIO
DELETE http://localhost:3000/api/users/10
Authorization: Bearer {{admin_token}}


###LOGEARSE
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identifier": "super.admin", 
  "password": "UnaContraseñaFuerte1235",
  "userType": "admin"
}



###LISTAR TIPOS DE VEHICULO
GET http://localhost:3000/api/type-vehicles

###GUARDAR TIPO DE VEHICULO
POST http://localhost:3000/api/type-vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX3R5cGUiOiJhZG1pbiIsInVzZXJuYW1lIjoic3VwZXIuYWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtcHJlc2EuY29tIiwiaWF0IjoxNzU0OTQ3ODE0LCJleHAiOjE3NTQ5NTE0MTR9.FH91trveog8KG3mLUDqSCygRCTppccDemHDfEyyABQ0
Content-Type: application/json

{
    "name": "Camioneta 4x4",
    "code": "C-4X4"
}

###Obtener Tipo de Vehículo por ID
GET http://localhost:3000/api/type-vehicles/1

###EDITAR TIPO DE VEHICULO
PUT http://localhost:3000/api/type-vehicles/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwidXNlcl90eXBlIjoiY2xpZW50IiwidXNlcm5hbWUiOiJjbGllbnRlLW1pbmEteHl6IiwiZW1haWwiOiJjbGllbnRlLnh5ekBleGFtcGxlLmNvbSIsImlhdCI6MTc1NDk0MDg3NywiZXhwIjoxNzU0OTQ0NDc3fQ.B4DtA4hOFGkGiGvhi8mjw4Rf1bj8lJbMpRgpLtdCd10
Content-Type: application/json

{
    "name": "Camioneta Pickup 4x4"
}

###ELIMINAR TIPO DE VEHICULO
DELETE http://localhost:3000/api/type-vehicles/1



###CREAR PRODUCTO 
POST http://localhost:3000/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX3R5cGUiOiJhZG1pbiIsInVzZXJuYW1lIjoic3VwZXIuYWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtcHJlc2EuY29tIiwiaWF0IjoxNzU0OTQ3ODE0LCJleHAiOjE3NTQ5NTE0MTR9.FH91trveog8KG3mLUDqSCygRCTppccDemHDfEyyABQ0
Content-Type: application/json

{
    "name": "Gas GLP Industrial",
    "code": 1001,
    "type_vehicle_id": 1,
    "type_unit": "KG",
    "spec_sheet_url": "https://example.com/especificaciones/gas-glp-industrial.pdf"
}

###LISTAR PRODUCTOS
GET http://localhost:3000/api/products


###LISTAR PRODUCTOS CON TYPO DE VEHICULO INCLUIDO
GET http://localhost:3000/api/products?includeTypeVehicle=true

###OBTENER UN PRODUCTO POR ID
GET http://localhost:3000/api/products/1

###MODIFICAR PRODUCTO
PUT http://localhost:3000/api/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX3R5cGUiOiJhZG1pbiIsInVzZXJuYW1lIjoic3VwZXIuYWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtcHJlc2EuY29tIiwiaWF0IjoxNzU0OTQ3ODE0LCJleHAiOjE3NTQ5NTE0MTR9.FH91trveog8KG3mLUDqSCygRCTppccDemHDfEyyABQ0
Content-Type: application/json

{
    "name": "Gas GLP Residencial",
    "type_unit": "Litro"
}

###ELIMINAR PRODUCTO 
DELETE http://localhost:3000/api/products/1



###CREAR PEDIDO
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "user_id": 2,
  "product_id": 3,
  "status": "pending",
  "orderDates": [
    {
      "delivery_date": "2025-08-10",
      "quantity": 20,
      "status": "pending"
    },
    {
      "delivery_date": "2025-08-12",
      "quantity": 15,
      "status": "pending"
    }
  ]
}

# {
#   "user_id": 2,
#   "product_id": 1,
#   "status": "pending",
#   "orderDates": [
#     {
#       "delivery_date": "2025-08-10",
#       "quantity": 10,
#       "status": "pending"
#     },
#     {
#       "delivery_date": "2025-08-12",
#       "quantity": 5,
#       "status": "pending"
#     }
#   ]
# }

###LISTAR PEDIDOS
GET http://localhost:3000/api/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX3R5cGUiOiJhZG1pbiIsInVzZXJuYW1lIjoic3VwZXIuYWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtcHJlc2EuY29tIiwiaWF0IjoxNzU1NzI2OTEyLCJleHAiOjE3NTU3MzA1MTJ9.cIl4MUFR_LnoHtaKXC5MS7hCn_FyuYfc5yYz_wqCq6U


###LISTAR PEDIDOS POR USUARIO Y MES
GET http://localhost:3000/api/orders/by-user-and-month?user_id=2&year=2025&month=8&day=15
Authorization: Bearer {{admin_token}}

###LISTAR PEDIDOS
GET http://localhost:3000/api/orders

###OBTENER PEDIDO POR ID
GET http://localhost:3000/api/orders/9
Authorization: Bearer {{admin_token}}


###EDITAR PEDIDO CON NUEVOS ORDER DATES
PUT http://localhost:3000/api/orders/6
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "status": "pending",
  "orderDates": [
    {
      "order_date_id": 1,
      "delivery_date": "2025-08-20T00:00:00.000Z",
      "quantity": 15,
      "status": "pending"
    },
    {
      "order_date_id": 2,
      "delivery_date": "2025-08-25T00:00:00.000Z",
      "quantity": 10,
      "status": "pending"
    },
    {
      "delivery_date": "2025-08-30T00:00:00.000Z",
      "quantity": 20,
      "status": "pending"
    }
  ]
}


###CREAR ORDER CHANGE REQUEST
POST http://localhost:3000/api/change-requests
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "order_date_id": 6,
  "request_type": "change_quantity",
  "change_quantity": 5,
  "admin_notes": "Necesitamos 5 unidades adicionales"
}

### Listar solicitudes (admin) - todas
GET http://localhost:3000/api/change-requests
Authorization: Bearer {{admin_token}}

### Obtener una solicitud por id (admin)
GET http://localhost:3000/api/change-requests/3
Authorization: Bearer {{admin_token}}

### Responder / actualizar solicitud (admin) - aprobar y aplicar cambio a orderDate
PUT http://localhost:3000/api/change-requests/3
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "status": "approved",
  "admin_notes": "Aprobado por control de stock",
  "admin_response_at": "2025-09-04T12:00:00.000Z",
  "apply_to_order_date": true
}

###Apis orden Dates
GET http://localhost:3000/api/order-dates
Authorization: Bearer {{admin_token}}

### Obtener un orden date por ID
GET http://localhost:3000/api/order-dates/1
Authorization: Bearer {{admin_token}}

### Crear un orden date
POST http://localhost:3000/api/order-dates
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "order_id": 9,
  "delivery_date": "2025-09-18",
  "quantity": 50,
  "status": "pending"
}

### Actualizar un orden date
PUT http://localhost:3000/api/order-dates/68
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "quantity": 25,
  "status": "pending"
}

### Eliminar un orden date
DELETE http://localhost:3000/api/order-dates/68
Authorization: Bearer {{admin_token}}

###Ordernet Change Requests por Id
GET http://localhost:3000/api/order-dates/10/change-requests
Authorization: Bearer {{admin_token}}

###Consulta para obtener la ultima cr de cada order date
POST http://localhost:3000/api/change-requests/query
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "order_date_ids": [6,88,79],
  "limit_per_order_date": 1
}

###Devuelve Orders que tienen al menos un OrderDate con una OrderChangeRequest.status = 'pending'.
GET http://localhost:3000/api/orders/with-pending-change-requests?year=2025&month=09
Authorization: Bearer {{admin_token}} 