###REGISTRAR USUARIO
POST http://localhost:3000/api/users
Content-Type: application/json

# {
#   "username": "cliente-mina-xyz",
#   "ruc": "10012345678",
#   "password": "PasswordSeguro123",
#   "email": "cliente.xyz@example.com",
#   "name": "Mina XYZ S.A.C.",
#   "phone": "987654321",
#   "userType": "client",
#   "status": "active",
#   "observations": "Nuevo cliente potencial",
#   "usualProductsNotes": "Necesita explosivos y aditivos",
#   "ccEmails": "gerencia.mina@example.com",
#   "leadTimeDays": 1
# }

{
  "username": "super.admin",
  "password": "UnaContraseñaFuerte1235",
  "email": "admin@empresa.com",
  "name": "Juan Pérez",
  "phone": "999888777",
  "userType": "admin",
  "status": "active"
}



###LISTAR USUARIOS
GET http://localhost:3000/api/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwidXNlcl90eXBlIjoiY2xpZW50IiwidXNlcm5hbWUiOiJjbGllbnRlLW1pbmEteHl6IiwiZW1haWwiOiJjbGllbnRlLnh5ekBleGFtcGxlLmNvbSIsImlhdCI6MTc1NDgwNTQzOSwiZXhwIjoxNzU0ODA5MDM5fQ.U-_VkQXu8dqah5qkbHRuYV7J02DM7uQds-gI3Uc_vEM


###EDITAR USUARIO
PUT http://localhost:3000/api/users/9
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwidXNlcl90eXBlIjoiY2xpZW50IiwidXNlcm5hbWUiOiJjbGllbnRlLW1pbmEteHl6IiwiZW1haWwiOiJjbGllbnRlLnh5ekBleGFtcGxlLmNvbSIsImlhdCI6MTc1NDgwNTQzOSwiZXhwIjoxNzU0ODA5MDM5fQ.U-_VkQXu8dqah5qkbHRuYV7J02DM7uQds-gI3Uc_vEM
Content-Type: application/json

{
  "name": "Juanjo",
  "phone": "999888778"
}

###ELIMINAR USUARIO
DELETE http://localhost:3000/api/users/10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwidXNlcl90eXBlIjoiY2xpZW50IiwidXNlcm5hbWUiOiJjbGllbnRlLW1pbmEteHl6IiwiZW1haWwiOiJjbGllbnRlLnh5ekBleGFtcGxlLmNvbSIsImlhdCI6MTc1NDgwNTQzOSwiZXhwIjoxNzU0ODA5MDM5fQ.U-_VkQXu8dqah5qkbHRuYV7J02DM7uQds-gI3Uc_vEM


###LOGEARSE
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "identifier": "super.admin", 
  "password": "UnaContraseñaFuerte1235",
  "userType": "admin"
}



###LISTAR TIPOS DE VEHICULO
GET http://localhost:3000/api/type-vehicles

###GUARDAR TIPO DE VEHICULO
POST http://localhost:3000/api/type-vehicles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX3R5cGUiOiJhZG1pbiIsInVzZXJuYW1lIjoic3VwZXIuYWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtcHJlc2EuY29tIiwiaWF0IjoxNzU0OTQ3ODE0LCJleHAiOjE3NTQ5NTE0MTR9.FH91trveog8KG3mLUDqSCygRCTppccDemHDfEyyABQ0
Content-Type: application/json

{
    "name": "Camioneta 4x4",
    "code": "C-4X4"
}

###Obtener Tipo de Vehículo por ID
GET http://localhost:3000/api/type-vehicles/1

###EDITAR TIPO DE VEHICULO
PUT http://localhost:3000/api/type-vehicles/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxMSwidXNlcl90eXBlIjoiY2xpZW50IiwidXNlcm5hbWUiOiJjbGllbnRlLW1pbmEteHl6IiwiZW1haWwiOiJjbGllbnRlLnh5ekBleGFtcGxlLmNvbSIsImlhdCI6MTc1NDk0MDg3NywiZXhwIjoxNzU0OTQ0NDc3fQ.B4DtA4hOFGkGiGvhi8mjw4Rf1bj8lJbMpRgpLtdCd10
Content-Type: application/json

{
    "name": "Camioneta Pickup 4x4"
}

###ELIMINAR TIPO DE VEHICULO
DELETE http://localhost:3000/api/type-vehicles/1



###CREAR PRODUCTO 
POST http://localhost:3000/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX3R5cGUiOiJhZG1pbiIsInVzZXJuYW1lIjoic3VwZXIuYWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtcHJlc2EuY29tIiwiaWF0IjoxNzU0OTQ3ODE0LCJleHAiOjE3NTQ5NTE0MTR9.FH91trveog8KG3mLUDqSCygRCTppccDemHDfEyyABQ0
Content-Type: application/json

{
    "name": "Gas GLP Industrial",
    "code": 1001,
    "type_vehicle_id": 1,
    "type_unit": "KG",
    "spec_sheet_url": "https://example.com/especificaciones/gas-glp-industrial.pdf"
}

###LISTAR PRODUCTOS
GET http://localhost:3000/api/products


###LISTAR PRODUCTOS CON TYPO DE VEHICULO INCLUIDO
GET http://localhost:3000/api/products?includeTypeVehicle=true

###OBTENER UN PRODUCTO POR ID
GET http://localhost:3000/api/products/1

###MODIFICAR PRODUCTO
PUT http://localhost:3000/api/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoxLCJ1c2VyX3R5cGUiOiJhZG1pbiIsInVzZXJuYW1lIjoic3VwZXIuYWRtaW4iLCJlbWFpbCI6ImFkbWluQGVtcHJlc2EuY29tIiwiaWF0IjoxNzU0OTQ3ODE0LCJleHAiOjE3NTQ5NTE0MTR9.FH91trveog8KG3mLUDqSCygRCTppccDemHDfEyyABQ0
Content-Type: application/json

{
    "name": "Gas GLP Residencial",
    "type_unit": "Litro"
}

###ELIMINAR PRODUCTO 
DELETE http://localhost:3000/api/products/1



###CREAR PEDIDO
POST http://localhost:3000/api/orders
Content-Type: application/json

{
  "user_id": 2,
  "product_id": 1,
  "status": "pending",
  "orderDates": [
    {
      "delivery_date": "2025-08-20",
      "quantity": 10,
      "status": "pending"
    },
    {
      "delivery_date": "2025-08-25",
      "quantity": 5,
      "status": "pending"
    }
  ]
}

###LISTAR PEDIDOS
GET http://localhost:3000/api/orders


###LISTAR PEDIDOS
GET http://localhost:3000/api/orders

###OBTENER PEDIDO POR ID
GET http://localhost:3000/api/orders/6

###EDITAR PEDIDO